#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Iface:
  def acl_match_spec_to_entry_hdl(self, sess_hdl, dev_tgt, match_spec, priority):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
     - match_spec
     - priority
    """
    pass

  def acl_table_add_with___meta_init_miss_action_acl__(self, sess_hdl, dev_tgt, match_spec, priority):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
     - match_spec
     - priority
    """
    pass

  def acl_table_add_with_nop(self, sess_hdl, dev_tgt, match_spec, priority):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
     - match_spec
     - priority
    """
    pass

  def acl_table_add_with__drop(self, sess_hdl, dev_tgt, match_spec, priority):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
     - match_spec
     - priority
    """
    pass

  def acl_table_modify_with___meta_init_miss_action_acl__(self, sess_hdl, dev_id, entry):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry
    """
    pass

  def acl_table_modify_with___meta_init_miss_action_acl___by_match_spec(self, sess_hdl, dev_tgt, match_spec, priority):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
     - match_spec
     - priority
    """
    pass

  def acl_table_modify_with_nop(self, sess_hdl, dev_id, entry):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry
    """
    pass

  def acl_table_modify_with_nop_by_match_spec(self, sess_hdl, dev_tgt, match_spec, priority):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
     - match_spec
     - priority
    """
    pass

  def acl_table_modify_with__drop(self, sess_hdl, dev_id, entry):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry
    """
    pass

  def acl_table_modify_with__drop_by_match_spec(self, sess_hdl, dev_tgt, match_spec, priority):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
     - match_spec
     - priority
    """
    pass

  def acl_table_delete(self, sess_hdl, dev_id, entry):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry
    """
    pass

  def acl_table_delete_by_match_spec(self, sess_hdl, dev_tgt, match_spec, priority):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
     - match_spec
     - priority
    """
    pass

  def update_countt_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def time32_in_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def write_time_in_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def time32_eg_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def write_time_eg_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def session_check_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def session_check_reverse_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def read_seq_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def read_seq_reverse_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def write_seq_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def session_init_table_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def session_complete_table_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def relay_session_table_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def inbound_tran_table_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def outbound_tran_table_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def report_table_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def set_heavy_hitter_count_table_1_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def set_heavy_hitter_count_table_2_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def acl_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def init_table_reset_default_entry(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def update_countt_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def time32_in_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def write_time_in_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def time32_eg_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def write_time_eg_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def session_check_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def session_check_reverse_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def read_seq_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def read_seq_reverse_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def write_seq_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def session_init_table_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def session_complete_table_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def relay_session_table_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def inbound_tran_table_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def outbound_tran_table_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def report_table_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def set_heavy_hitter_count_table_1_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def set_heavy_hitter_count_table_2_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def acl_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def init_get_entry_count(self, sess_hdl, dev_id):
    """
    Parameters:
     - sess_hdl
     - dev_id
    """
    pass

  def update_countt_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def update_countt_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def update_countt_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def time32_in_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def time32_in_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def time32_in_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def write_time_in_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def write_time_in_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def write_time_in_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def time32_eg_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def time32_eg_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def time32_eg_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def write_time_eg_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def write_time_eg_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def write_time_eg_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def session_check_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def session_check_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def session_check_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def session_check_reverse_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def session_check_reverse_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def session_check_reverse_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def read_seq_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def read_seq_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def read_seq_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def read_seq_reverse_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def read_seq_reverse_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def read_seq_reverse_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def write_seq_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def write_seq_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def write_seq_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def session_init_table_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def session_init_table_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def session_init_table_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def session_complete_table_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def session_complete_table_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def session_complete_table_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def relay_session_table_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def relay_session_table_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def relay_session_table_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def inbound_tran_table_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def inbound_tran_table_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

  def inbound_tran_table_get_entry(self, sess_hdl, dev_id, entry_hdl, read_from_hw):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - read_from_hw
    """
    pass

  def outbound_tran_table_get_first_entry_handle(self, sess_hdl, dev_tgt):
    """
    Parameters:
     - sess_hdl
     - dev_tgt
    """
    pass

  def outbound_tran_table_get_next_entry_handles(self, sess_hdl, dev_id, entry_hdl, n):
    """
    Parameters:
     - sess_hdl
     - dev_id
     - entry_hdl
     - n
    """
    pass

